<a href="https://colab.research.google.com/github/shubhamahajan4869/Netflix_Analysis/blob/main/Netflix_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# %pip install --upgrade plotly

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

In [ ]:
df_title = pd.read_csv("titles.csv")
df_credit = pd.read_csv("credits.csv")

In [ ]:
df_title.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,48,['documentation'],['US'],1.0,NaN,NaN,NaN,0.600,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
2,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,530877.0,18.216,7.8
3,tm70993,Life of Brian,MOVIE,"Brian Cohen is an average young Jewish man, bu...",1979,R,94,['comedy'],['GB'],NaN,tt0079470,8.0,392419.0,17.505,7.8
4,tm190788,The Exorcist,MOVIE,12-year-old Regan MacNeil begins to adapt an e...,1973,R,133,['horror'],['US'],NaN,tt0070047,8.1,391942.0,95.337,7.7

In [ ]:
df_credit.head()

   person_id       id             name                character   role
0       3748  tm84618   Robert De Niro            Travis Bickle  ACTOR
1      14658  tm84618     Jodie Foster            Iris Steensma  ACTOR
2       7064  tm84618    Albert Brooks                      Tom  ACTOR
3       3739  tm84618    Harvey Keitel  Matthew 'Sport' Higgins  ACTOR
4      48933  tm84618  Cybill Shepherd                    Betsy  ACTOR

In [ ]:
df = pd.merge(df_title, df_credit, on="id")
df.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,person_id,name,character,role
0,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2,3748,Robert De Niro,Travis Bickle,ACTOR
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2,14658,Jodie Foster,Iris Steensma,ACTOR
2,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2,7064,Albert Brooks,Tom,ACTOR
3,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2,3739,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR
4,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2,48933,Cybill Shepherd,Betsy,ACTOR

In [ ]:
df.shape

(77213, 19)

In [ ]:
df.columns

Index(['id', 'title', 'type', 'description', 'release_year',
       'age_certification', 'runtime', 'genres', 'production_countries',
       'seasons', 'imdb_id', 'imdb_score', 'imdb_votes', 'tmdb_popularity',
       'tmdb_score', 'person_id', 'name', 'character', 'role'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 77213 entries, 0 to 77212
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    77213 non-null  object
 1   title                 77212 non-null  object
 2   type                  77213 non-null  object
 3   release_year          77213 non-null  int64
 4   age_certification     46595 non-null  object
 5   runtime               77213 non-null  int64
 6   genres                77061 non-null  object
 7   production_countries  76496 non-null  object
 8   seasons               13976 non-null  float64
 9   imdb_id               73388 non-null  object
 10  imdb_score            72937 non-null  float64
 11  imdb_votes            72850 non-null  float64
 12  tmdb_popularity       77202 non-null  float64
 13  tmdb_score            76093 non-null  float64
 14  person_id             77213 non-null  int64
 15  name                  77213 non-null  object
 16  character             67586 non-null  object
 17  role                  77213 non-null  object
dtypes: float64(5), int64(3), object(10)
memory usage: 13.2+ MB

In [ ]:
df.genres.apply(pd.Series)
df.sample()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,person_id,name,character,role
40097,tm413955,A Fortunate Man,MOVIE,"On his quest for happiness, Per decides to lea...",2018,NaN,162,european,DK,NaN,tt8436026,7.2,6093.0,12.746,6.9,117488,Mette Munk Plum,Portnerske,ACTOR

In [ ]:
df.drop("seasons", axis=1, inplace=True)
df.sample(5)

,id,title,type,release_year,age_certification,runtime,genres,production_countries,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,person_id,name,character,role
41138,tm347850,SPF-18,MOVIE,2017,PG-13,75,romance,US,tt7296862,3.2,5122.0,17.736,4.4,748803,Alex Israel,NaN,DIRECTOR
55336,tm855483,Have a Good Trip: Adventures in Psychedelics,MOVIE,2020,NaN,85,documentation,US,tt12133722,6.8,7578.0,14.485,6.8,16671,Adam Horovitz,Self,ACTOR
62231,tm849599,Furtive,MOVIE,2020,NaN,84,thriller,AR,tt11287390,5.1,320.0,2.167,6.5,353647,Héctor Bordoni,Furtivo 1,ACTOR
14958,ts6506,The Borgias,SHOW,2011,TV-MA,51,crime,HU,tt1582457,7.9,50556.0,23.185,7.6,15527,Jemima West,Vittoria,ACTOR
54613,ts215378,Love 101,SHOW,2020,TV-14,46,romance,TR,tt10516352,7.5,13797.0,12.956,8.2,199542,Kaan Urgancıoğlu,Kemal,ACTOR

In [ ]:
df.isna().values.any()

True

In [ ]:
df.duplicated().values.any()

False

In [ ]:
data = df.dropna()
data.sample(5)

,id,title,type,release_year,age_certification,runtime,genres,production_countries,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,person_id,name,character,role
66873,tm1142224,The House,MOVIE,2022,R,97,drama,GB,tt11703050,6.8,12270.0,8.347,7.0,5578,Matthew Goode,Raymond (voice),ACTOR
52716,tm849005,The Willoughbys,MOVIE,2020,PG,92,comedy,CA,tt5206260,6.3,17878.0,18.838,7.2,8718,Ricky Gervais,The Cat (voice),ACTOR
2288,tm65686,U.S. Marshals,MOVIE,1998,PG-13,126,crime,US,tt0120873,6.5,103263.0,28.657,6.5,10772,Johnny Lee Davenport,Deputy Marshal Henry,ACTOR
17567,tm140877,The Imitation Game,MOVIE,2014,PG-13,113,war,GB,tt2084970,8.0,748654.0,46.710,8.0,4971,Rory Kinnear,Detective Robert Nock,ACTOR
13792,tm50018,Looper,MOVIE,2012,R,119,drama,US,tt1276104,7.4,566791.0,48.347,6.9,8174,James Landry Hébert,Looper,ACTOR

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41213 entries, 0 to 77001
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    41213 non-null  object
 1   title                 41213 non-null  object
 2   type                  41213 non-null  object
 3   release_year          41213 non-null  int64
 4   age_certification     41213 non-null  object
 5   runtime               41213 non-null  int64
 6   genres                41213 non-null  object
 7   production_countries  41213 non-null  object
 8   imdb_id               41213 non-null  object
 9   imdb_score            41213 non-null  float64
 10  imdb_votes            41213 non-null  float64
 11  tmdb_popularity       41213 non-null  float64
 12  tmdb_score            41213 non-null  float64
 13  person_id             41213 non-null  int64
 14  name                  41213 non-null  object
 15  character             41213 non-null  object
 16  role                  41213 non-null  object
dtypes: float64(4), int64(3), object(10)
memory usage: 5.7+ MB

In [ ]:
type_cat = data.groupby("type", as_index=False).agg({"id":pd.Series.count})
type_cat.head()

    type     id
0  MOVIE  31060
1   SHOW  10153

In [ ]:
fig = px.pie(labels=type_cat.type, 
             values=type_cat.id,
             title="Movies vs Shows",
             names=type_cat.type,)
fig.update_traces(textposition='outside', textinfo='percent+label')
fig.show()

In [ ]:
genres_cat = data.groupby("genres", as_index=False).agg({"id":pd.Series.count})
genres_cat=genres_cat.sort_values("id", ascending=False)
genres_cat.head()

      genres    id
5      drama  9232
2     comedy  6606
16  thriller  4092
0     action  3285
3      crime  2783

In [ ]:
bar = px.bar(x=genres_cat.genres, 
             y=genres_cat.id, 
             title='Top Genres',
             hover_name=genres_cat.genres,
             color=genres_cat.id,
             color_continuous_scale='Agsunset')

bar.update_layout(xaxis_title='Genre',
yaxis_title='Count',
coloraxis_showscale=False)

bar.show()

In [ ]:
rating = df.groupby("age_certification", as_index=False).agg({"id":pd.Series.count})
rating = rating.sort_values("id", ascending=False)
rating.head()

  age_certification     id
4                 R  15853
3             PG-13  11508
7             TV-MA   6581
2                PG   5134
5             TV-14   3518

In [ ]:
rating_fig = px.pie(labels=rating.age_certification, 
             values=rating.id,
             title="Rating",
             names=rating.age_certification,)
rating_fig.update_traces(textposition='outside', textinfo='percent+label')
rating_fig.show()

In [ ]:
character = df.groupby("name", as_index=False).agg({"id":pd.Series.count})
character = character.sort_values("id", ascending=False)[:20]
character.head(10)

                        name  id
45343         Shah Rukh Khan  30
6561             Boman Irani  25
25890    Kareena Kapoor Khan  25
4137             Anupam Kher  25
48211       Takahiro Sakurai  22
38619           Paresh Rawal  22
41311            Raúl Campos  21
36705    Nawazuddin Siddiqui  21
40366  Priyanka Chopra Jonas  21
21200              Jan Suter  20

In [ ]:
char_bar = px.bar(x=character.name, 
             y=character.id, 
             title='Number of Movies/Shows performed by Actor',
             hover_name=character.name,
             color=character.id,
             color_continuous_scale='Agsunset')

char_bar.update_layout(xaxis_title='Name',
yaxis_title='Count',
coloraxis_showscale=False)

char_bar.show()

In [ ]:
country = df.groupby(["production_countries", "type"], as_index=False).agg({"id":pd.Series.count})
country = country.sort_values("id", ascending=False)[:50]
country.head(10)

    production_countries   type     id
147                   US  MOVIE  28914
65                    IN  MOVIE   6953
148                   US   SHOW   4025
47                    GB  MOVIE   3383
82                    KR   SHOW   1940
76                    JP  MOVIE   1898
45                    FR  MOVIE   1895
40                    ES  MOVIE   1836
77                    JP   SHOW   1745
19                    CA  MOVIE   1735

In [ ]:
country_bar = px.bar(y=country.production_countries, 
             x=country.id,
             orientation="h",
             title='Top Countries ',
             hover_name=country.production_countries,
             color=country["type"],
             color_continuous_scale='Agsunset')

country_bar.update_layout(xaxis_title='Country',
yaxis_title='Count',
coloraxis_showscale=False)

country_bar.show()

In [ ]:
df_title.isna().values.any()

True

In [ ]:
df_titles = df_title.dropna()
df_titles.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
5,ts22164,Monty Python's Flying Circus,SHOW,A British sketch comedy series with the shows ...,1969,TV-14,30,"['comedy', 'european']",['GB'],4.0,tt0063929,8.8,72895.0,12.919,8.3
29,ts45948,Monty Python's Fliegender Zirkus,SHOW,Monty Python's Fliegender Zirkus consisted of ...,1972,TV-MA,43,['comedy'],[],1.0,tt0202477,8.1,2144.0,1.490,7.0
47,ts20681,Seinfeld,SHOW,A stand-up comedian and his three offbeat frie...,1989,TV-PG,24,['comedy'],['US'],9.0,tt0098904,8.9,302700.0,128.743,8.3
55,ts22082,Knight Rider,SHOW,"Michael Long, an undercover police officer, is...",1982,TV-PG,51,"['action', 'scifi', 'crime', 'drama']",['US'],4.0,tt0083437,6.9,33760.0,44.378,7.5
57,ts21715,Thomas & Friends,SHOW,Thomas & Friends is a British children's telev...,1984,TV-Y,10,"['family', 'comedy', 'music', 'action', 'anima...",['GB'],24.0,tt0086815,6.5,4948.0,49.384,6.6

In [ ]:
top_rated = df_titles.sort_values("imdb_score", ascending=False)
top20_shows = top_rated[:20]

In [ ]:
top_bar = px.bar(x=top20_shows.title, 
             y=top20_shows.imdb_score, 
             title='Top 20 Netflix Shows',
             hover_name=top20_shows.title,
             color=top20_shows.imdb_score,
             color_continuous_scale='Agsunset')

top_bar.update_layout(xaxis_title='Name',
yaxis_title='Score',
coloraxis_showscale=False)

top_bar.show()

In [ ]:
df.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,person_id,name,character,role
0,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2,3748,Robert De Niro,Travis Bickle,ACTOR
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2,14658,Jodie Foster,Iris Steensma,ACTOR
2,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2,7064,Albert Brooks,Tom,ACTOR
3,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2,3739,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR
4,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2,48933,Cybill Shepherd,Betsy,ACTOR